services:
  nginx:
    image: nginx:1.27.1-alpine3.20
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.hawari.dev`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
