services:
  traefik:
    image: traefik:v3.1.2
    restart: always
    container_name: traefik-proxy
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=$BASIC_AUTH"
    environment:
      BASIC_AUTH: ${BASIC_AUTH}
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-network

volumes:
  letsencrypt:

networks:
  traefik-network:
    external: true
