services:
  db:
    image: bitnami/redis:7.4.1
    restart: always
    container_name: redis-db
    expose:
      - ${REDIS_PORT_NUMBER}
    environment:
      REDIS_PORT_NUMBER: ${REDIS_PORT_NUMBER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p $REDIS_PORT_NUMBER -a '$REDIS_PASSWORD'  ping | grep PONG"]
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
