services:
  db:
    image: bitnami/redis:7.4.1
    restart: always
    container_name: redis-db
    ports:
      - 6379:6379 # publish default redis port
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a '$REDIS_PASSWORD'  ping | grep PONG"]
      start_period: 60s
      interval: 3600s
      timeout: 5s
      retries: 5
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
